"""
Strategy Executor / 策略執行器

Executes strategies from strategies.json and generates signals.
執行 strategies.json 中的策略並產生訊號。
"""

import json
import logging
from typing import Dict, List, Optional, Any
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path

from signals.engine import Signal, SignalType, SignalLevel
from app.strategy_conditions import StrategyConditions, ConditionResult


logger = logging.getLogger(__name__)


@dataclass
class StrategySignal:
    """Signal generated by a strategy / 策略產生的訊號"""
    strategy_id: str
    strategy_name: str
    strategy_type: str
    symbol: str
    signal_type: SignalType
    level: SignalLevel
    reason: str
    warning: str
    conditions_passed: int
    conditions_total: int
    details: Dict[str, Any] = field(default_factory=dict)


def load_strategies(config_path: str = "config/strategies.json") -> List[Dict[str, Any]]:
    """Load strategies from config file / 從設定檔載入策略"""
    try:
        with open(config_path) as f:
            data = json.load(f)
        return data.get("strategies", [])
    except Exception as e:
        logger.error(f"Failed to load strategies from {config_path}: {e}")
        return []


def load_merged_genetic_strategies() -> List[Dict[str, Any]]:
    """
    Load manual strategies plus promoted V2 Champions only.

    Legacy ``strategies_genetic.json`` files are deliberately ignored because
    they may contain research winners that were never manually promoted.
    """
    manual = [
        strategy
        for strategy in load_strategies("config/strategies.json")
        if strategy.get("source") != "genetic"
    ]
    try:
        from app.genetic_engine.archive import StrategyArchive
        from app.genetic_engine.chromosome_v2 import StrategyChromosomeV2
        from app.genetic_engine.converter import convert_to_strategy_json

        from app.genetic_engine.chromosome_v2 import built_in_default_chromosome
        archive = StrategyArchive()
        champions = archive.get_all_champions()
        if champions:
            runtime_genetic = [
                convert_to_strategy_json(
                    StrategyChromosomeV2.from_dict(record.chromosome_data)
                )
                for record in champions.values()
            ]
        else:
            # No Champion yet — use deterministic built-in default
            runtime_genetic = [
                convert_to_strategy_json(built_in_default_chromosome())
            ]
        logger.info(
            "Loaded runtime strategies: %d manual + %d Champion/default genetic",
            len(manual),
            len(runtime_genetic),
        )
        return manual + runtime_genetic
    except Exception as exc:
        logger.error(f"Failed to resolve Champion runtime strategy: {exc}")
        return manual


def get_enabled_strategies(strategies: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """Filter enabled strategies / 篩選啟用的策略"""
    return [s for s in strategies if s.get("enabled", False)]


class StrategyExecutor:
    """
    Strategy executor / 策略執行器
    
    Loads strategies from config and evaluates them against market data.
    從設定載入策略並根據市場資料評估。
    
    Supports genetic strategies when use_genetic=True / 當 use_genetic=True 時支持基因策略
    """
    
    def __init__(self, config_path: str = "config/strategies.json", use_genetic: bool = False):
        """
        Initialize executor / 初始化執行器
        
        Args:
            config_path: Path to strategies config
            use_genetic: If True, load from merged genetic config if available
        """
        self.config_path = config_path
        self.use_genetic = use_genetic
        self.conditions = StrategyConditions()
        self._strategies: List[Dict[str, Any]] = []
        self._load_strategies()
    
    def _load_strategies(self) -> None:
        """Load strategies from config / 從設定載入策略"""
        if self.use_genetic:
            self._strategies = load_merged_genetic_strategies()
        else:
            self._strategies = load_strategies(self.config_path)
        enabled = get_enabled_strategies(self._strategies)
        logger.info(f"Loaded {len(self._strategies)} strategies, {len(enabled)} enabled")
    
    def reload_strategies(self) -> None:
        """Reload strategies from config / 重新載入策略"""
        self._load_strategies()
    
    @property
    def strategies(self) -> List[Dict[str, Any]]:
        """Get all strategies / 取得所有策略"""
        return self._strategies
    
    @property
    def enabled_strategies(self) -> List[Dict[str, Any]]:
        """Get enabled strategies / 取得啟用的策略"""
        return get_enabled_strategies(self._strategies)
    
    def get_genetic_strategies(self) -> List[Dict[str, Any]]:
        """Get only genetic strategies / 取得僅基因策略"""
        return [s for s in self._strategies if s.get("source") == "genetic"]
    
    def get_manual_strategies(self) -> List[Dict[str, Any]]:
        """Get only manual strategies / 取得僅手動策略"""
        return [s for s in self._strategies if s.get("source") == "manual"]
    
    def execute_for_symbol(
        self,
        symbol: str,
        market_data: Dict[str, Any]
    ) -> List[StrategySignal]:
        """
        Execute all enabled strategies for a symbol / 執行所有啟用策略
        
        Args:
            symbol: Trading pair / 交易對
            market_data: Market data dictionary containing:
                - price: Current price
                - ma5, ma20, ma240: Moving averages
                - volume_ratio: Volume ratio
                - candles: List of candle data
                - closes: List of close prices
                
        Returns:
            List of strategy signals
        """
        signals = []
        
        for strategy in self.enabled_strategies:
            # Check if strategy applies to this symbol
            strategy_symbols = strategy.get("symbols", [])
            if strategy_symbols and symbol not in strategy_symbols:
                continue
            
            # Execute strategy
            signal = self._execute_strategy(strategy, symbol, market_data)
            if signal:
                signals.append(signal)
        
        return signals
    
    def _execute_strategy(
        self,
        strategy: Dict[str, Any],
        symbol: str,
        market_data: Dict[str, Any]
    ) -> Optional[StrategySignal]:
        """
        Execute a single strategy / 執行單一策略
        
        Args:
            strategy: Strategy configuration
            symbol: Trading pair
            market_data: Market data
            
        Returns:
            StrategySignal if conditions pass, None otherwise
        """
        strategy_id = strategy["id"]
        strategy_name = strategy["name"]
        strategy_type = strategy.get("type", "unknown")
        conditions = strategy.get("conditions", [])
        parameters = strategy.get("parameters", {})
        signal_type_str = strategy.get("signal_type", "trend_long")
        signal_level_str = strategy.get("signal_level", "watch_only")
        warning = strategy.get("warning", "")
        
        # Map signal type string to enum
        signal_type = self._map_signal_type(strategy_id)
        signal_level = self._map_signal_level(signal_level_str)
        
        # Check all conditions
        condition_results = self.conditions.check_all_conditions(
            conditions, market_data, parameters
        )
        
        passed = sum(1 for r in condition_results if r.result == ConditionResult.PASSED)
        failed = sum(1 for r in condition_results if r.result == ConditionResult.FAILED)
        missing = sum(1 for r in condition_results if r.result == ConditionResult.MISSING_DATA)
        not_impl = sum(1 for r in condition_results if r.result == ConditionResult.NOT_IMPLEMENTED)
        
        # Build details
        details = {
            "conditions": [
                {
                    "condition": r.condition,
                    "result": r.result.value,
                    "message": r.message,
                    "details": r.details
                }
                for r in condition_results
            ],
            "passed": passed,
            "failed": failed,
            "missing_data": missing,
            "not_implemented": not_impl
        }
        
        # Determine if strategy triggers
        # All conditions must pass, and none can fail
        all_passed = self.conditions.strategy_passed(condition_results)
        
        if all_passed:
            # Build reason from passed conditions
            reason_parts = [r.message for r in condition_results if r.result == ConditionResult.PASSED]
            reason = " | ".join(reason_parts) if reason_parts else f"{strategy_name} conditions met"
            
            return StrategySignal(
                strategy_id=strategy_id,
                strategy_name=strategy_name,
                strategy_type=strategy_type,
                symbol=symbol,
                signal_type=signal_type,
                level=signal_level,
                reason=reason,
                warning=warning or f"Strategy: {strategy_name}",
                conditions_passed=passed,
                conditions_total=len(conditions),
                details=details
            )
        
        return None
    
    def _map_signal_type(self, strategy_id: str) -> SignalType:
        """Map strategy_id to unique SignalType enum / 將策略 ID 對應到唯一 SignalType"""
        mapping = {
            "ma_cross_trend": SignalType.MA_CROSS_TREND,
            "ma_cross_trend_short": SignalType.MA_CROSS_TREND_SHORT,
            "contrarian_watch_overheated": SignalType.CONTRARIAN_OVERHEATED,
            "contrarian_watch_oversold": SignalType.CONTRARIAN_OVERSOLD,
            "hilbert_cycle": SignalType.HILBERT_CYCLE,
            "stochastic_breakout": SignalType.STOCHASTIC_BREAKOUT,
            "rsi_trend": SignalType.RSI_TREND,
            "bb_mean_reversion": SignalType.BB_MEAN_REVERSION,
            "ema_cross_fast": SignalType.EMA_CROSS_FAST,
            "rsi_mid_bounce": SignalType.RSI_MID_BOUNCE,
            "volume_spike": SignalType.VOLUME_SPIKE,
            "price_channel_break": SignalType.PRICE_CHANNEL_BREAK,
            "momentum_divergence": SignalType.MOMENTUM_DIVERGENCE,
        }
        return mapping.get(strategy_id, SignalType.MA_CROSS_TREND)
    
    def _map_signal_level(self, signal_level_str: str) -> SignalLevel:
        """Map string to SignalLevel enum / 將字串對應到 SignalLevel 列舉"""
        mapping = {
            "confirmed": SignalLevel.CONFIRMED,
            "watch_only": SignalLevel.WATCH_ONLY,
        }
        return mapping.get(signal_level_str, SignalLevel.WATCH_ONLY)
    
    def get_strategy_summary(self) -> Dict[str, Any]:
        """Get summary of loaded strategies / 取得已載入策略摘要"""
        enabled = self.enabled_strategies
        
        return {
            "total": len(self._strategies),
            "enabled": len(enabled),
            "disabled": len(self._strategies) - len(enabled),
            "strategies": [
                {
                    "id": s["id"],
                    "name": s["name"],
                    "type": s.get("type", "unknown"),
                    "enabled": s.get("enabled", False),
                    "symbols": s.get("symbols", []),
                    "conditions_count": len(s.get("conditions", [])),
                }
                for s in self._strategies
            ]
        }
