"""
Strategy Executor / 策略執行器

Executes strategies from strategies.json and generates signals.
執行 strategies.json 中的策略並產生訊號。
"""

import json
import logging
from typing import Dict, List, Optional, Any
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path

from signals.engine import Signal, SignalType, SignalLevel
from app.strategy_conditions import StrategyConditions, ConditionResult


logger = logging.getLogger(__name__)


@dataclass
class StrategySignal:
    """Signal generated by a strategy / 策略產生的訊號"""
    strategy_id: str
    strategy_name: str
    strategy_type: str
    symbol: str
    signal_type: SignalType
    level: SignalLevel
    reason: str
    warning: str
    conditions_passed: int
    conditions_total: int
    details: Dict[str, Any] = field(default_factory=dict)


def load_strategies(config_path: str = "config/strategies.json") -> List[Dict[str, Any]]:
    """Load strategies from config file / 從設定檔載入策略"""
    try:
        with open(config_path) as f:
            data = json.load(f)
        return data.get("strategies", [])
    except Exception as e:
        logger.error(f"Failed to load strategies from {config_path}: {e}")
        return []


def get_enabled_strategies(strategies: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """Filter enabled strategies / 篩選啟用的策略"""
    return [s for s in strategies if s.get("enabled", False)]


class StrategyExecutor:
    """
    Strategy executor / 策略執行器
    
    Loads strategies from config and evaluates them against market data.
    從設定載入策略並根據市場資料評估。
    """
    
    def __init__(self, config_path: str = "config/strategies.json"):
        """
        Initialize executor / 初始化執行器
        
        Args:
            config_path: Path to strategies config
        """
        self.config_path = config_path
        self.conditions = StrategyConditions()
        self._strategies: List[Dict[str, Any]] = []
        self._load_strategies()
    
    def _load_strategies(self) -> None:
        """Load strategies from config / 從設定載入策略"""
        self._strategies = load_strategies(self.config_path)
        enabled = get_enabled_strategies(self._strategies)
        logger.info(f"Loaded {len(self._strategies)} strategies, {len(enabled)} enabled")
    
    def reload_strategies(self) -> None:
        """Reload strategies from config / 重新載入策略"""
        self._load_strategies()
    
    @property
    def strategies(self) -> List[Dict[str, Any]]:
        """Get all strategies / 取得所有策略"""
        return self._strategies
    
    @property
    def enabled_strategies(self) -> List[Dict[str, Any]]:
        """Get enabled strategies / 取得啟用的策略"""
        return get_enabled_strategies(self._strategies)
    
    def execute_for_symbol(
        self,
        symbol: str,
        market_data: Dict[str, Any]
    ) -> List[StrategySignal]:
        """
        Execute all enabled strategies for a symbol / 執行所有啟用策略
        
        Args:
            symbol: Trading pair / 交易對
            market_data: Market data dictionary containing:
                - price: Current price
                - ma5, ma20, ma240: Moving averages
                - volume_ratio: Volume ratio
                - candles: List of candle data
                - closes: List of close prices
                
        Returns:
            List of strategy signals
        """
        signals = []
        
        for strategy in self.enabled_strategies:
            # Check if strategy applies to this symbol
            strategy_symbols = strategy.get("symbols", [])
            if strategy_symbols and symbol not in strategy_symbols:
                continue
            
            # Execute strategy
            signal = self._execute_strategy(strategy, symbol, market_data)
            if signal:
                signals.append(signal)
        
        return signals
    
    def _execute_strategy(
        self,
        strategy: Dict[str, Any],
        symbol: str,
        market_data: Dict[str, Any]
    ) -> Optional[StrategySignal]:
        """
        Execute a single strategy / 執行單一策略
        
        Args:
            strategy: Strategy configuration
            symbol: Trading pair
            market_data: Market data
            
        Returns:
            StrategySignal if conditions pass, None otherwise
        """
        strategy_id = strategy["id"]
        strategy_name = strategy["name"]
        strategy_type = strategy.get("type", "unknown")
        conditions = strategy.get("conditions", [])
        parameters = strategy.get("parameters", {})
        signal_type_str = strategy.get("signal_type", "trend_long")
        signal_level_str = strategy.get("signal_level", "watch_only")
        warning = strategy.get("warning", "")
        
        # Map signal type string to enum
        signal_type = self._map_signal_type(signal_type_str)
        signal_level = self._map_signal_level(signal_level_str)
        
        # Check all conditions
        condition_results = self.conditions.check_all_conditions(
            conditions, market_data, parameters
        )
        
        passed = sum(1 for r in condition_results if r.result == ConditionResult.PASSED)
        failed = sum(1 for r in condition_results if r.result == ConditionResult.FAILED)
        missing = sum(1 for r in condition_results if r.result == ConditionResult.MISSING_DATA)
        not_impl = sum(1 for r in condition_results if r.result == ConditionResult.NOT_IMPLEMENTED)
        
        # Build details
        details = {
            "conditions": [
                {
                    "condition": r.condition,
                    "result": r.result.value,
                    "message": r.message,
                    "details": r.details
                }
                for r in condition_results
            ],
            "passed": passed,
            "failed": failed,
            "missing_data": missing,
            "not_implemented": not_impl
        }
        
        # Determine if strategy triggers
        # All conditions must pass, and none can fail
        all_passed = self.conditions.strategy_passed(condition_results)
        
        if all_passed:
            # Build reason from passed conditions
            reason_parts = [r.message for r in condition_results if r.result == ConditionResult.PASSED]
            reason = " | ".join(reason_parts) if reason_parts else f"{strategy_name} conditions met"
            
            return StrategySignal(
                strategy_id=strategy_id,
                strategy_name=strategy_name,
                strategy_type=strategy_type,
                symbol=symbol,
                signal_type=signal_type,
                level=signal_level,
                reason=reason,
                warning=warning or f"Strategy: {strategy_name}",
                conditions_passed=passed,
                conditions_total=len(conditions),
                details=details
            )
        
        return None
    
    def _map_signal_type(self, signal_type_str: str) -> SignalType:
        """Map string to SignalType enum / 將字串對應到 SignalType 列舉"""
        mapping = {
            "trend_long": SignalType.TREND_LONG,
            "trend_short": SignalType.TREND_SHORT,
            "contrarian_watch_overheated": SignalType.CONTRARIAN_WATCH_OVERHEATED,
            "contrarian_watch_oversold": SignalType.CONTRARIAN_WATCH_OVERSOLD,
            "cycle": SignalType.CYCLE,
            "breakout": SignalType.BREAKOUT,
            "momentum": SignalType.MOMENTUM,
            "mean_reversion": SignalType.MEAN_REVERSION,
            "reversal_long": SignalType.REVERSAL_LONG,
            "breakout_long": SignalType.BREAKOUT_LONG,
        }
        return mapping.get(signal_type_str, SignalType.TREND_LONG)
    
    def _map_signal_level(self, signal_level_str: str) -> SignalLevel:
        """Map string to SignalLevel enum / 將字串對應到 SignalLevel 列舉"""
        mapping = {
            "confirmed": SignalLevel.CONFIRMED,
            "watch_only": SignalLevel.WATCH_ONLY,
        }
        return mapping.get(signal_level_str, SignalLevel.WATCH_ONLY)
    
    def get_strategy_summary(self) -> Dict[str, Any]:
        """Get summary of loaded strategies / 取得已載入策略摘要"""
        enabled = self.enabled_strategies
        
        return {
            "total": len(self._strategies),
            "enabled": len(enabled),
            "disabled": len(self._strategies) - len(enabled),
            "strategies": [
                {
                    "id": s["id"],
                    "name": s["name"],
                    "type": s.get("type", "unknown"),
                    "enabled": s.get("enabled", False),
                    "symbols": s.get("symbols", []),
                    "conditions_count": len(s.get("conditions", [])),
                }
                for s in self._strategies
            ]
        }
